version: "3"

services:
    client:
        image: nginx
        container_name: webserver
        ports:
            - 8000:80
        volumes:
            - /home/pantor/repos/duocuc/TECNOLOGIAS_DE_VIRTUALIZACION_002D/parcial2/www/index.html:/usr/share/nginx/html/index.html